admin=admin:Rane@123,1234:asd,12345:as 
camera_ipaddress=192.168.0.111
camera_username=admin
camera_password=Rane@123
plc_ipaddress=192.168.0.3
read_camera=0
frames_store_path1=F:\I4.0_Project\Goggle_detection\exe_tests\Detections\
frames_store_path=D:\I4.0\Goggle_detection\File_access_test\
folder_name=Violation_frames
read_video=2.mp4 
ckpt_head=3
ckpt_goggle=11
x=750
y=100
width=960
height=1280
threshold_head=.8 
threshold_goggle=.9
show_height=720
show_width=1280
head_aligned_crop_width=800
head_aligned_crop_height=600
model_folder_name=model_SPR4.1
model_head_folder_name=model_Head
model_goggle_folder_name=Goggle_800x600_1
label_map_name=label_map.pbtxt
delay_time_in_milliseconds=0
undetection_limit=11
fluctuation_frames_tuning=1
time_delay_for_display_label_update_in_milliseconds=200
plc_db_number=4
delay_for_save_in_milliseconds=100
true_count=0
head_width_to_identify_as_a_backhead=300
buzzer_delay=10
head_count_limit=25
plc_communication_delay_in_milliseconds=50
goggle_inside_head_tolerance=16
folder_count_to_show_in_graph=5
